server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service:3306/user?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: MysqlRootPassword
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service:8848
        # 延迟注册（单位毫秒）
        register-enabled: true
        # 重点！添加启动延迟，等待Nacos客户端初始化完成
        register-delay: 5000   # 延迟5秒注册
  security:
    oauth2:
      authorizationserver:
        client:
          login-client:
            registration:
              client-id: login-client
              client-secret: "$2a$10$Th55TmYNTmFULjxeWJhUEuEhx6u4gyuLH44ZSP6rh0vUXX6etUcfi" #openid-connect
              client-authentication-methods:
                - client_secret_basic
              authorizationGrantTypes:
                - authorization_code
                - refresh_token
                - client_credentials
              redirectUris:
                - http://gateway-service/login/oauth2/code/login-client
                - http://gateway-service/authorized
              post-logout-redirect-uris:
                - http://gateway-service/
              scopes:
                - openid
                - profile
                - message:read
                - message:write
            require-authorization-consent:  true
          messaging-client:
            registration:
              client-id: messaging-client
              client-secret: secret
              client-authentication-methods:
                - client_secret_basic
              authorizationGrantTypes:
                - client_credentials
              scopes:
                - message:read
                - message:write
      resourceserver:
        jwt:
          jwk-set-uri: http://user-service/oauth2/jwks
