server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service:3306/payment?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: MysqlRootPassword
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service:8848
        # 延迟注册（单位毫秒）
        register-enabled: true
        # 重点！添加启动延迟，等待Nacos客户端初始化完成
        register-delay: 5000   # 延迟5秒注册

alipay:
  app-id: 9021000142686486
  private-key: "/sandbox/app_private_key.txt"
  alipay-public-key: "/sandbox/alipay_public_key.txt"
  protocol: https
  gateway-host: openapi-sandbox.dl.alipaydev.com/gateway.do
  notify-url: https://www.laria.cn/e-commerce-platform/payment/alipay/notify
  return-url: https://www.laria.cn/e-commerce-platform/payment/alipay/return