server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.119:50001/payment?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root@mc
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.119:8848
        username: nacos
        password: nacos

alipay:
  app-id: 9021000142686486
  private-key: "D:/sandbox/app_private_key.txt"
  alipay-public-key: "D:/sandbox/alipay_public_key.txt"
  protocol: https
  gateway-host: openapi-sandbox.dl.alipaydev.com/gateway.do
  notify-url: https://www.laria.cn/e-commerce-platform/payment/alipay/notify
  return-url: https://www.laria.cn/e-commerce-platform/payment/alipay/return